when:
- event: push
  branch: ${CI_REPO_DEFAULT_BRANCH}

steps:
- name: release-helper
  image: registry.yewolf.fr/wrapper/wrap/mirror.gcr.io/woodpeckerci/plugin-ready-release-go/3.4.0/with/ghcr.io/yyewolf/woodpecker-plugins/github-token-wrapper/latest:latest
  settings:
    release_branch: ${CI_REPO_DEFAULT_BRANCH}
    forge_type: github
    git_email: robertowo@yewolf.fr
    mtls_service_url: https://github-token-svc:8443/token
    mtls_ca_cert:
      from_secret: MTLS_CA_CERT
    mtls_client_cert:
      from_secret: MTLS_CLIENT_CERT
    mtls_client_key:
      from_secret: MTLS_CLIENT_KEY

services:
- name: github-token-svc
  image: ghcr.io/yyewolf/woodpecker-plugins/github-app-token-svc
  ports:
  - 8443
  settings:
    github_app_id:
      from_secret: GITHUB_APP_ID
    github_installation_id:
      from_secret: GITHUB_INSTALL_ID
    github_private_key_pem:
      from_secret: GITHUB_APP_PEM
    mtls_ca_cert:
      from_secret: MTLS_CA_CERT
    mtls_server_cert:
      from_secret: MTLS_SERVER_CERT
    mtls_server_key:
      from_secret: MTLS_SERVER_KEY
